import { describe, expect, it } from 'vitest';
import { classify, COVERS, GROUP_ORDER, groupIndex } from '../src/classify.js';

/** [written class name (variants already stripped), expected group] */
const CASES: Array<[string, string | null]> = [
  // display / layout statics
  ['flex', 'display'],
  ['hidden', 'display'],
  ['inline-grid', 'display'],
  ['table-row', 'display'],
  ['absolute', 'position'],
  ['sticky', 'position'],
  ['invisible', 'visibility'],
  ['box-border', 'box'],
  ['isolate', 'isolation'],
  ['float-start', 'float'],
  ['clear-both', 'clear'],
  ['container', 'container'],
  ['sr-only', 'sr'],
  ['aspect-video', 'aspect'],
  ['columns-3', 'columns'],
  ['break-after-page', 'break-after'],
  ['break-before-avoid', 'break-before'],
  ['break-inside-avoid', 'break-inside'],
  // inset / z
  ['inset-0', 'inset'],
  ['inset-x-4', 'inset-x'],
  ['inset-y-4', 'inset-y'],
  ['top-1/2', 'top'],
  ['right-0', 'right'],
  ['bottom-8', 'bottom'],
  ['left-[3px]', 'left'],
  ['start-2', 'start'],
  ['end-2', 'end'],
  ['z-50', 'z'],
  // flex / grid
  ['flex-row', 'flex-direction'],
  ['flex-col-reverse', 'flex-direction'],
  ['flex-wrap', 'flex-wrap'],
  ['flex-nowrap', 'flex-wrap'],
  ['flex-1', 'flex'],
  ['flex-auto', 'flex'],
  ['flex-[2_2_0%]', 'flex'],
  ['grow', 'grow'],
  ['grow-0', 'grow'],
  ['shrink', 'shrink'],
  ['shrink-0', 'shrink'],
  ['basis-1/2', 'basis'],
  ['order-2', 'order'],
  ['grid-cols-3', 'grid-cols'],
  ['grid-rows-2', 'grid-rows'],
  ['grid-flow-row-dense', 'grid-flow'],
  ['col-auto', 'col'],
  ['col-span-2', 'col-span'],
  ['col-start-1', 'col-start'],
  ['col-end-3', 'col-end'],
  ['row-auto', 'row'],
  ['row-span-full', 'row-span'],
  ['row-start-2', 'row-start'],
  ['row-end-4', 'row-end'],
  ['auto-cols-fr', 'auto-cols'],
  ['auto-rows-min', 'auto-rows'],
  ['gap-4', 'gap'],
  ['gap-x-2', 'gap-x'],
  ['gap-y-2', 'gap-y'],
  // alignment
  ['justify-center', 'justify-content'],
  ['justify-items-start', 'justify-items'],
  ['justify-self-end', 'justify-self'],
  ['items-center', 'items'],
  ['content-center', 'content-align'],
  ['content-none', 'content'],
  ['content-[attr(before)]', 'content'],
  ['self-stretch', 'self'],
  ['place-content-between', 'place-content'],
  ['place-items-center', 'place-items'],
  ['place-self-auto', 'place-self'],
  // spacing
  ['p-4', 'p'],
  ['px-6', 'px'],
  ['py-1', 'py'],
  ['pt-2', 'pt'],
  ['pr-2', 'pr'],
  ['pb-2', 'pb'],
  ['pl-2', 'pl'],
  ['ps-2', 'ps'],
  ['pe-2', 'pe'],
  ['m-auto', 'm'],
  ['mx-auto', 'mx'],
  ['my-2', 'my'],
  ['mt-8', 'mt'],
  ['mr-3', 'mr'],
  ['mb-px', 'mb'],
  ['ml-[7px]', 'ml'],
  ['ms-1', 'ms'],
  ['me-1', 'me'],
  ['space-x-4', 'space-x'],
  ['space-y-2', 'space-y'],
  // sizing
  ['w-full', 'w'],
  ['w-[.5rem]', 'w'],
  ['min-w-0', 'min-w'],
  ['max-w-prose', 'max-w'],
  ['h-screen', 'h'],
  ['min-h-full', 'min-h'],
  ['max-h-64', 'max-h'],
  ['size-8', 'size'],
  // typography
  ['font-sans', 'font-family'],
  ['font-display', 'font-family'],
  ['font-bold', 'font-weight'],
  ['font-normal', 'font-weight'],
  ['font-[600]', 'font-weight'],
  ['font-[family-name:var(--f)]', 'font-family'],
  ['text-xs', 'font-size'],
  ['text-lg', 'font-size'],
  ['text-2xl', 'font-size'],
  ['text-[12px]', 'font-size'],
  ['text-[length:var(--s)]', 'font-size'],
  ['text-[size:14px]', 'font-size'],
  ['text-[calc(1rem+2px)]', 'font-size'],
  ['text-center', 'text-align'],
  ['text-justify', 'text-align'],
  ['text-red-500', 'text-color'],
  ['text-white/80', 'text-color'],
  ['text-[#bada55]', 'text-color'],
  ['text-[rgb(0,0,0)]', 'text-color'],
  ['text-[color:var(--c)]', 'text-color'],
  ['text-[var(--c)]', 'text-color'],
  ['italic', 'font-style'],
  ['antialiased', 'font-smoothing'],
  ['tabular-nums', 'font-variant'],
  ['tracking-tight', 'tracking'],
  ['leading-7', 'leading'],
  ['indent-4', 'indent'],
  ['align-middle', 'align'],
  ['whitespace-nowrap', 'whitespace'],
  ['break-words', 'word-break'],
  ['hyphens-auto', 'hyphens'],
  ['list-disc', 'list-type'],
  ['list-inside', 'list-position'],
  ['list-outside', 'list-position'],
  ['uppercase', 'text-transform'],
  ['truncate', 'text-overflow'],
  ['text-balance', 'text-wrap'],
  ['underline', 'text-decoration'],
  ['decoration-wavy', 'decoration-style'],
  ['decoration-from-font', 'decoration-w'],
  ['decoration-2', 'decoration-w'],
  ['decoration-[3px]', 'decoration-w'],
  ['decoration-sky-500', 'decoration-color'],
  ['underline-offset-4', 'underline-offset'],
  // backgrounds
  ['bg-fixed', 'bg-attachment'],
  ['bg-clip-text', 'bg-clip'],
  ['bg-origin-border', 'bg-origin'],
  ['bg-blend-multiply', 'bg-blend'],
  ['bg-red-500', 'bg-color'],
  ['bg-[#123456]', 'bg-color'],
  ['bg-left-top', 'bg-position'],
  ['bg-no-repeat', 'bg-repeat'],
  ['bg-cover', 'bg-size'],
  ['bg-gradient-to-r', 'bg-image'],
  ['bg-none', 'bg-image'],
  ['bg-[url(/img.png)]', 'bg-image'],
  ['from-purple-400', 'from'],
  ['via-pink-500', 'via'],
  ['to-red-500', 'to'],
  // borders
  ['rounded', 'rounded'],
  ['rounded-lg', 'rounded'],
  ['rounded-[12px]', 'rounded'],
  ['rounded-t', 'rounded-t'],
  ['rounded-tl-sm', 'rounded-tl'],
  ['rounded-se-xl', 'rounded-se'],
  ['border', 'border-w'],
  ['border-2', 'border-w'],
  ['border-[3px]', 'border-w'],
  ['border-x', 'border-w-x'],
  ['border-t-2', 'border-w-t'],
  ['border-b-[3px]', 'border-w-b'],
  ['border-r-red-500', 'border-color-r'],
  ['border-rose-500', 'border-color'],
  ['border-[#fff]', 'border-color'],
  ['border-solid', 'border-style'],
  ['border-collapse', 'border-collapse'],
  ['border-spacing-2', 'border-spacing'],
  ['divide-x', 'divide-x'],
  ['divide-x-2', 'divide-x'],
  ['divide-y-4', 'divide-y'],
  ['divide-dashed', 'divide-style'],
  ['divide-slate-200', 'divide-color'],
  ['outline', 'outline-style'],
  ['outline-none', 'outline-style'],
  ['outline-2', 'outline-w'],
  ['outline-pink-500', 'outline-color'],
  ['outline-offset-2', 'outline-offset'],
  ['ring', 'ring-w'],
  ['ring-inset', 'ring-w'],
  ['ring-2', 'ring-w'],
  ['ring-sky-500', 'ring-color'],
  ['ring-offset-2', 'ring-offset-w'],
  ['ring-offset-slate-50', 'ring-offset-color'],
  // effects
  ['shadow', 'shadow'],
  ['shadow-md', 'shadow'],
  ['shadow-none', 'shadow'],
  ['shadow-[0_35px_60px_-15px_rgba(0,0,0,0.3)]', 'shadow'],
  ['shadow-[#50d71e]', 'shadow-color'],
  ['shadow-[rgb(0,0,0)]', 'shadow-color'],
  ['shadow-cyan-500/50', 'shadow-color'],
  ['opacity-75', 'opacity'],
  ['mix-blend-multiply', 'mix-blend'],
  // filters
  ['blur', 'blur'],
  ['blur-sm', 'blur'],
  ['brightness-150', 'brightness'],
  ['contrast-125', 'contrast'],
  ['drop-shadow', 'drop-shadow'],
  ['drop-shadow-md', 'drop-shadow'],
  ['grayscale', 'grayscale'],
  ['grayscale-0', 'grayscale'],
  ['hue-rotate-90', 'hue-rotate'],
  ['invert', 'invert'],
  ['invert-0', 'invert'],
  ['saturate-50', 'saturate'],
  ['sepia', 'sepia'],
  ['sepia-0', 'sepia'],
  ['backdrop-blur', 'backdrop-blur'],
  ['backdrop-blur-sm', 'backdrop-blur'],
  ['backdrop-hue-rotate-15', 'backdrop-hue-rotate'],
  ['backdrop-opacity-60', 'backdrop-opacity'],
  ['backdrop-frobnicate', null],
  // tables
  ['table-auto', 'table-layout'],
  ['caption-top', 'caption'],
  ['border-separate', 'border-collapse'],
  // transitions / animation
  ['transition', 'transition'],
  ['transition-colors', 'transition'],
  ['transition-[width]', 'transition'],
  ['duration-300', 'duration'],
  ['ease-in-out', 'ease'],
  ['delay-150', 'delay'],
  ['animate-spin', 'animate'],
  // transforms
  ['transform', 'transform'],
  ['transform-none', 'transform'],
  ['scale-95', 'scale'],
  ['scale-x-50', 'scale-x'],
  ['scale-y-50', 'scale-y'],
  ['rotate-45', 'rotate'],
  ['translate-x-2', 'translate-x'],
  ['translate-y-1/2', 'translate-y'],
  ['skew-x-6', 'skew-x'],
  ['skew-y-3', 'skew-y'],
  ['origin-top-left', 'origin'],
  // interactivity
  ['accent-pink-500', 'accent'],
  ['appearance-none', 'appearance'],
  ['cursor-pointer', 'cursor'],
  ['caret-blue-500', 'caret'],
  ['pointer-events-none', 'pointer-events'],
  ['resize', 'resize'],
  ['resize-y', 'resize'],
  ['scroll-smooth', 'scroll-behavior'],
  ['select-none', 'select'],
  ['touch-pan-x', 'touch'],
  ['will-change-transform', 'will-change'],
  // svg
  ['fill-current', 'fill'],
  ['stroke-2', 'stroke-w'],
  ['stroke-[3px]', 'stroke-w'],
  ['stroke-red-400', 'stroke-color'],
  // overflow / object
  ['object-cover', 'object-fit'],
  ['object-scale-down', 'object-fit'],
  ['object-top', 'object-position'],
  ['overflow-hidden', 'overflow'],
  ['overflow-x-auto', 'overflow-x'],
  ['overflow-y-scroll', 'overflow-y'],
  ['overscroll-contain', 'overscroll'],
  ['overscroll-x-none', 'overscroll-x'],
  ['overscroll-y-auto', 'overscroll-y'],
  // arbitrary properties
  ['[color:red]', 'arb:color'],
  ['[mask-type:luminance]', 'arb:mask-type'],
  ['[foo]', null],
  ['[oops', null],
  // unknown
  ['btn', null],
  ['foo-bar', null],
  ['', null],
];

describe('classify', () => {
  it.each(CASES)('classify(%j) → %j', (name, group) => {
    expect(classify(name)).toBe(group);
  });

  it('emits only groups that have a canonical sort position', () => {
    for (const [name] of CASES) {
      const group = classify(name);
      if (group !== null) {
        expect(Number.isInteger(groupIndex(group)), `group "${group}" from "${name}"`).toBe(true);
      }
    }
  });

  it('lists only known groups in COVERS', () => {
    for (const [shorthand, specifics] of Object.entries(COVERS)) {
      expect(GROUP_ORDER).toContain(shorthand);
      for (const specific of specifics) {
        expect(GROUP_ORDER, `covered group "${specific}"`).toContain(specific);
      }
    }
  });
});

describe('groupIndex', () => {
  it('places unknown utilities after everything else', () => {
    expect(groupIndex(null)).toBe(GROUP_ORDER.length + 1);
  });

  it('places arbitrary properties after known groups', () => {
    expect(groupIndex('arb:color')).toBe(GROUP_ORDER.length);
  });

  it('respects the canonical list order', () => {
    expect(groupIndex('display')).toBeLessThan(groupIndex('p'));
    expect(groupIndex('p')).toBeLessThan(groupIndex('bg-color'));
  });
});
